# action.yml
name: 'AKS Create Action'
description: 'Create an AKS Cluster'
branding:
  icon: anchor
  color: blue
inputs:
  ACCOUNT_NAME:
    description: 'Account name for CosmosDB instance'
    required: true
  RESOURCE_GROUP_NAME:  # id of input
    description: 'Resource Group for cluster'
    required: true
  ARM_SUBSCRIPTION_ID: # id of input
    description: 'subscription ID'
    required: true
  ARM_TENANT_ID: # id of input
    description: 'tenant ID'
    required: true
  SP_USERNAME: # id of input
    description: 'service principle username to log in'
    required: true
  SP_SECRET: # id of input
    description: 'service principle password to log in'
    required: true
  MSI_OBJECT_ID: # id of input
    description: 'MSI object id (service principle id)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ACCOUNT_NAME }}
    - ${{ inputs.RESOURCE_GROUP_NAME }}
    - ${{ inputs.ARM_SUBSCRIPTION_ID }}
    - ${{ inputs.ARM_TENANT_ID }}
    - ${{ inputs.SP_USERNAME }}
    - ${{ inputs.SP_SECRET }}
    - ${{ inputs.MSI_OBJECT_ID }}